project:
  type: website
  output-dir: docs

website: 
  title: "Ana's R portfolio"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Anazuniga57/codingwithan-.git
      - icon: twitter
        href: https://twitter.com/MattCrumpLab
format:
  html:
    theme: sketchy
    css: styles.css

editor: visual

